### ISSUE TITLE
Can´t install on Windows 10

### ISSUE THREAD

**Issue by carloslimaborges** [DMSec/coffeetvshow#1]
> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "i"
> npm ERR! node v6.6.0
> npm ERR! npm  v3.10.3
> npm ERR! code ELIFECYCLE
> 
> npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the bcrypt package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs bcrypt
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls bcrypt
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     D:\desenvolvimento\temp\coffeetvshow\npm-debug.log

npm-debug.log:

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
> 1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
> 1 verbose cli   'start' ]
> 2 info using npm@3.10.3
> 3 info using node@v6.6.0
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle coffeetvshow@0.0.1~prestart: coffeetvshow@0.0.1
> 6 silly lifecycle coffeetvshow@0.0.1~prestart: no script for prestart, continuing
> 7 info lifecycle coffeetvshow@0.0.1~start: coffeetvshow@0.0.1
> 8 verbose lifecycle coffeetvshow@0.0.1~start: unsafe-perm in lifecycle true
> 9 verbose lifecycle coffeetvshow@0.0.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\desenvolvimento\temp\coffeetvshow\node_modules.bin;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Brackets\command;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\carlo\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Sublime Text 3;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\carlo\AppData\Roaming\npm;C:\Program Files\MongoDB\Server\3.2\bin;C:\Users\carlo\AppData\Local\atom\bin
> 10 verbose lifecycle coffeetvshow@0.0.1~start: CWD: D:\desenvolvimento\temp\coffeetvshow
> 11 silly lifecycle coffeetvshow@0.0.1~start: Args: [ '/d /s /c', 'node server.js' ]
> 12 silly lifecycle coffeetvshow@0.0.1~start: Returned: code: 1  signal: null
> 13 info lifecycle coffeetvshow@0.0.1~start: Failed to exec start script
> 14 verbose stack Error: coffeetvshow@0.0.1 start: `node server.js`
> 14 verbose stack Exit status 1
> 14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at EventEmitter.emit (events.js:191:7)
> 14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at ChildProcess.emit (events.js:191:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:877:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 15 verbose pkgid coffeetvshow@0.0.1
> 16 verbose cwd D:\desenvolvimento\temp\coffeetvshow
> 17 error Windows_NT 10.0.14393
> 18 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
> 19 error node v6.6.0
> 20 error npm  v3.10.3
> 21 error code ELIFECYCLE
> 22 error coffeetvshow@0.0.1 start: `node server.js`
> 22 error Exit status 1
> 23 error Failed at the coffeetvshow@0.0.1 start script 'node server.js'.
> 23 error Make sure you have the latest version of node.js and npm installed.
> 23 error If you do, this is most likely a problem with the coffeetvshow package,
> 23 error not with npm itself.
> 23 error Tell the author that this fails on your system:
> 23 error     node server.js
> 23 error You can get information on how to open an issue for this project with:
> 23 error     npm bugs coffeetvshow
> 23 error Or if that isn't available, you can get their info via:
> 23 error     npm owner ls coffeetvshow
> 23 error There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

**Comment by douglasmsi** [comment]
@xaxim sorry, but I didn't see your message before. I changed the language to Java with other features.
